# SPDX-License-Identifier: AGPL-3.0-only
[workspace]
resolver = "2"
members = [
    "crates/dragnet-core",
    # Fazlarda eklenecek:
    # "crates/dragnet-dht",
    # "crates/dragnet-meta",
    # "crates/dragnet-store",
    # "crates/dragnet-api",
    # "bin/dragnetd",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
repository = ""
authors = ["<TELİF HAKKI SAHİBİ>"]

[workspace.dependencies]
# Ortak bağımlılıklar fazlarda buraya toplanacak (tokio, serde, tracing, ...).
serde = { version = "1", features = ["derive"] }
